### PR TITLE
prelaunchr with Rails 4.2 and Ruby 2.2.0

### PR DESCRIPTION
**Pull request by wardpenney**
Works on deployment to heroku. Thanks for a great product!

### CODE REVIEW

**Comment by bbozo** [comment]
Yes please (y)

**Comment by kennedysgarage** [comment]
:8ball:  When you get a sec, would you mind merging this.

**Comment by KevinColemanInc** [comment]
:+1:

**Comment by gwfc** [comment]
Hey folks,

Sorry about posting here for this.

But . . . 

#1 Do you know of a few good places that have community support for this prelaunchr (for questions etc)?

#2 I have everything edited to my liking and ready except for the Facebook share text/image (I know it should be straight forward but for some reason I can not find that last part). I put together these quick annotated screenshots. Could you let me know if you know where I can find where the edit can be made and actually show up on future clicks of the FB icon share button? Twitter is working fine.

http://screencast.com/t/2zmgXPxUJv69

and

http://screencast.com/t/Wmok93njQ27

:)

Greg

**Comment by ckhatton** [comment]
Facebook uses the open graph meta that's in the `<head>` section of the layout `application.html.erb`. Facebook caches in the same way that Google indexes the web, any changes you make will take time to propagate on Facebook. So if you change the image or text, you likely won't see an immediate change.

You can test what it is currently caching for your app here... https://developers.facebook.com/tools/debug/

**Comment by gwfc** [comment]
@ckhatton Fantastic! That now makes sense. I know about the application.html.erb but did not about the other stuff you mentioned. I was looking for in-app cache all over the place to clear etc. It is good to go now and I fix a couple of things with the debug link you gave too. Nice. Do you know of any active forums/communities dedicated to this prelaunchr app I may look into becoming a part of that are good?

**Comment by ckhatton** [comment]
:+1:
No I don't, sorry.
:octocat:

**Comment by irubnich** [comment]
Hi @wardpenney. Thanks for this great PR! I'd love to get this merged in with all the latest bells and whistles. I merged in a PR with some specs yesterday and would love to get this branch up to date with those specs passing. I also pushed an upgrade to Ruby 2.3 / Rails 3.2.22.2

The versions in this branch that need updating are:
1. Rails should be bumped to 4.2.5.2
2. ActiveAdmin should be bumped to 1.0.0.pre2 (no need for that external `inhereted_resources` dependency anymore!)

There are also some merge conflicts with the new stuff, nothing too crazy.

I attempted to upgrade to Rails 4.2 locally and it seemed fine but I trust you with the minutia of the upgrade. Once all this is done I'll give it a look-over.

Thank you in advance! If you can't get this done for whatever reason please let me know and I'll put some work into it and get a review going.

- Ilya

**Comment by ckhatton** [comment]
:+1: There's also styling edits and a fix to the mailer that I want to make... But I don't know when I'll ever get round to it :disappointed:

**Comment by phamdt** [comment]
i can fetch this branch and do all the leg work of merge conflicts, etc. if wardpenney doesn't have time for it

**Comment by irubnich** [comment]
I'm all for it @phamdt

**Comment by phamdt** [comment]
close?

**Pull request closed without merging**
